[workspace]
members = [
    "calorie_counting",
    "rock_paper_scissors",
    "rucksack_reorganization",
    "supply_stacks",
    "camp_cleanup",
    "tuning_trouble",
    "no_space_left_on_device",

    "runner",
]
