[package]
name = "runner"
version = "0.0.0"
edition = "2021"

[dependencies]
paste = "1.0"

chumsky = "0.8"

core = { path = "../core" }

calorie_counting = { path = "../calorie_counting" }
rock_paper_scissors = { path = "../rock_paper_scissors" }
rucksack_reorganization = { path = "../rucksack_reorganization" }
supply_stacks = { path = "../supply_stacks" }
